all:
  children:
    prepared_servers:
      hosts:
        test-vm01:
          luks_device: /dev/vdb
        target-vm01:
          luks_device: /dev/xvdf
    cpu_performance_servers:
      hosts:
        test-vm01:
        target-vm01:
